version: 2

project_name: synthfs

builds:
  - id: synthfs
    main: ./cmd/synthfs
    binary: synthfs
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: synthfs-archive
    ids: [synthfs]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "synthfs-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - "README.md"
      - "LICENSE"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

brews:
  - ids: [synthfs-archive]
    name: synthfs
    repository:
      owner: arthur-debert
      name: homebrew-tools
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    # Use debug directory if DEBUG env var is set, otherwise use Formula
    directory: "{{ if .Env.DEBUG }}debug{{ else }}Formula{{ end }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/arthur-debert/synthfs"
    description: "Description of your CLI tool"
    license: "MIT"
    test: |
      system "#{bin}/synthfs --help"
    install: |
      bin.install "synthfs"

# nFPM packages (deb, rpm, etc.)
# https://goreleaser.com/customization/nfpm/
nfpms:
  - id: synthfs-deb
    ids: [synthfs]
    package_name: synthfs
    formats:
      - deb
    vendor: "Arthur Debert"
    homepage: "https://github.com/arthur-debert/synthfs"
    maintainer: "Arthur Debert <arthur@debert.xyz>"
    description: "Description of your CLI tool"
    license: "MIT"

env:
  - PKG_NAME={{ .Env.PKG_NAME }}
