name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Set environment variables
        run: |
          echo "PKG_NAME=go-synthfs" >> $GITHUB_ENV
          echo "GH_USER=arthur-debert" >> $GITHUB_ENV
          echo "GIT_REPO=arthur-debert/go-synthfs" >> $GITHUB_ENV
          echo "Package name: go-synthfs"
          echo "Repository: arthur-debert/go-synthfs"

      - name: Build binary first
        run: scripts/build
        env:
          PKG_NAME: go-synthfs

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          PKG_NAME: go-synthfs 